//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.EMF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentHistory
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Graph { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AttachId { get; set; }
        public Nullable<int> UserStoryId { get; set; }
        public string state { get; set; }
        public Nullable<int> version { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual UserStory UserStory { get; set; }
    }
}
