//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.EMF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprintHistory
    {
        public int Id { get; set; }
        public Nullable<int> sprintId { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public string closedBy { get; set; }
        public int version { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
